import mongoose from "mongoose";

const complaintSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    imageUrl: { type: String, required: true },
    userDescription: { type: String }, // what the citizen typed

    // Location
    location: {
      lat: { type: Number, required: true },
      lng: { type: Number, required: true },
      address: { type: String },
      district: { type: String },
    },

    // AI-generated fields (filled by Gemini Vision after upload)
    aiCategory: {
      type: String,
      enum: [
        "Pothole",
        "Road Crack",
        "Waterlogging",
        "Fallen Tree",
        "Broken Traffic Signal",
        "Missing Traffic Sign",
        "Garbage on Road",
        "Other",
      ],
    },
    aiSeverity: {
      type: String,
      enum: ["Low", "Medium", "High", "Critical"],
    },
    aiDescription: { type: String }, // structured description generated by AI
    aiConfidenceNote: { type: String }, // brief reasoning from the model, optional

    status: {
      type: String,
      enum: ["Pending", "In Progress", "Resolved"],
      default: "Pending",
    },

    isAnonymous: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export default mongoose.model("Complaint", complaintSchema);
